// <auto-generated />
namespace MvcProject_Lema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class abc2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(abc2));
        
        string IMigrationMetadata.Id
        {
            get { return "202403301955331_abc2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
